name: egnn-test
channels:
  - conda-forge
  - pyg
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.7
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - docker-pycreds=0.4.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.12
  - packaging=23.1
  - pathtools=0.1.2
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=3.10.0
  - pooch=1.7.0
  - protobuf=3.20.3
  - psutil=5.9.0
  - pycparser=2.21
  - pyg=2.4.0
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.18
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=68.2.2
  - six=1.16.0
  - smmap=4.0.0
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=2.0.0
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tqdm=4.65.0
  - typing_extensions=4.9.0
  - urllib3=1.26.18
  - wandb=0.16.2
  - wheel=0.41.2
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - torch-cluster==1.6.3+pt20cu118
      - torch-scatter==2.1.2+pt20cu118
      - torch-sparse==0.6.18+pt20cu118
